# ----
# Site

title: XT DOC
description: XT Interface documentation.
url: https://xt-com.github.io/xt4-api/
google_analytics_key:
permalink: pretty
baseurl:

# -----
# Build

timezone: Etc/UTC

collections:
  documentation:
    title: Access Description
    type: spot
    language: en
    position_number: 1
  market:
    title: Market
    type: spot
    language: en
    position_number: 2
  order:
    title: Order
    type: spot
    language: en
    position_number: 3
  trade:
    title: Trade
    type: spot
    language: en
    position_number: 4
  balance:
    title: Balance
    type: spot
    language: en
    position_number: 5
  deposit_withdrawal:
    title: Deposit/Withdrawal
    type: spot
    language: en
    position_number: 6
  websocket_public:
    title: WEBSOCKET(public)
    type: spot
    language: en
    position_number: 7
  websocket_private:
    title: WEBSOCKET(private)
    type: spot
    language: en
    position_number: 8
  documentation_cn:
    title: 接入说明
    type: spot
    language: cn
    position_number: 9
  market_cn:
    title: 市场数据
    type: spot
    language: cn
    position_number: 10
  order_cn:
    title: 订单
    type: spot
    language: cn
    position_number: 11
  trade_cn:
    title: 成交
    type: spot
    language: cn
    position_number: 12
  balance_cn:
    title: 资产
    type: spot
    language: cn
    position_number: 13
  deposit_withdrawal_cn:
    title: 充值/提现
    type: spot
    language: cn
    position_number: 14
  websocket_public_cn:
    title: WEBSOCKET(public)
    type: spot
    language: cn
    position_number: 15
  websocket_private_cn:
    title: WEBSOCKET(private)
    type: spot
    language: cn
    position_number: 16

  futures_documentation:
    title: Access Description
    type: futures
    language: en
    position_number: 1
  futures_quotes:
    title: Market data
    type: futures
    language: en
    position_number: 2
  futures_order:
    title: Order
    type: futures
    language: en
    position_number: 3
  futures_entrust:
    title: Entrust
    type: futures
    language: en
    position_number: 4
  futures_user:
    title: User
    type: futures
    language: en
    position_number: 5
  # futures_market_websocket:
  #   title: WEBSOCKET
  #   type: futures
  #   language: en
  #   position_number: 6
  futures_market_websocket_v2:
    title: WEBSOCKET(V2)
    type: futures
    language: en
    position_number: 7
  futures_user_websocket:
    title: USER WEBSOCKET
    type: futures
    language: en
    position_number: 8
  futures_documentation_cn:
    title: 接入说明
    type: futures
    language: cn
    position_number: 1
  futures_quotes_cn:
    title: 行情数据
    type: futures
    language: cn
    position_number: 2
  futures_order_cn:
    title: 限价委托和市价委托
    type: futures
    language: cn
    position_number: 3
  futures_entrust_cn:
    title: 计划委托与止盈止损
    type: futures
    language: cn
    position_number: 4
  futures_user_cn:
    title: 用户相关
    type: futures
    language: cn
    position_number: 5
  # futures_market_websocket_cn:
  #   title: 行情WEBSOCKET
  #   type: futures
  #   language: cn
  #   position_number: 6
  futures_market_websocket_v2_cn:
    title: 行情WEBSOCKET(V2)
    type: futures
    language: cn
    position_number: 7
  futures_user_websocket_cn:
    title: 用户WEBSOCKET
    type: futures
    language: cn
    position_number: 8
  third_party_document:
    title: Access Description
    type: third_party
    language: en
    position_number: 1
  third_party_document_cn:
    title: 接入说明
    type: third_party
    language: cn
    position_number: 1

  third_party_user_reg:
    title: User Registration
    type: third_party
    language: en
    position_number: 2
  third_party_user_reg_cn:
    title: 用户注册
    type: third_party
    language: cn
    position_number: 2

  third_party_authorization_page:
    title: Authorization Page
    type: third_party
    language: en
    position_number: 3
  third_party_authorization_page_cn:
    title: 授权页跳转
    type: third_party
    language: cn
    position_number: 3

  third_party_oauth2:
    title: OAuth Interface
    type: third_party
    language: en
    position_number: 4
  third_party_oauth2_cn:
    title: OAuth2接口
    type: third_party
    language: cn
    position_number: 4
  third_party_copy_trade:
    title: Copy Trade
    type: third_party
    language: en
    position_number: 5
  third_party_copy_trade_cn:
    title: 跟单接口
    type: third_party
    language: cn
    position_number: 5

  user_center_documentation:
    title: Access Description
    type: user_center
    language: en
    position_number: 1
  user_center_account:
    title: Account
    type: user_center
    language: en
    position_number: 2
  user_center_apiKey:
    title: ApiKey
    type: user_center
    language: en
    position_number: 3

  user_center_documentation_cn:
    title: 接入说明
    type: user_center
    language: cn
    position_number: 4
  user_center_account_cn:
    title: 账户
    type: user_center
    language: cn
    position_number: 5
  user_center_apikey_cn:
    title: ApiKey
    type: user_center
    language: cn
    position_number: 6

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - CNAME
  - favicon.ico
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - robots.txt


defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  - scope:
      type: "documentation"
    values:
      _hide_content: true
  -
    scope:
      type: "market"
    values:
      _hide_content: true
  -
    scope:
      type: "order"
    values:
      _hide_content: true
  - scope:
      type: "trade"
    values:
      _hide_content: true
  -
    scope:
      type: "balance"
    values:
      _hide_content: true
  -
    scope:
      type: "deposit_withdrawal"
    values:
      _hide_content: true
  -
    scope:
      type: "websocket_public"
    values:
      _hide_content: true
  - scope:
      type: "websocket_private"
    values:
      _hide_content: true
  - scope:
      type: "documentation_cn"
    values:
      _hide_content: true
  -
    scope:
      type: "market_cn"
    values:
      _hide_content: true
  -
    scope:
      type: "order_cn"
    values:
      _hide_content: true
  - scope:
      type: "trade_cn"
    values:
      _hide_content: true
  -
    scope:
      type: "balance_cn"
    values:
      _hide_content: true
  -
    scope:
      type: "deposit_withdrawal_cn"
    values:
      _hide_content: true
  -
    scope:
      type: "websocket_public_cn"
    values:
      _hide_content: true
  - scope:
      type: "websocket_private_cn"
    values:
      _hide_content: true

  - scope:
      type: "futures_documentation"
    values:
      _hide_content: true
  - scope:
      type: "futures_quotes"
    values:
      _hide_content: true
  - scope:
      type: "futures_order"
    values:
      _hide_content: true
  - scope:
      type: "futures_entrust"
    values:
      _hide_content: true
  - scope:
      type: "futures_user"
    values:
      _hide_content: true
  # - scope:
  #     type: "futures_market_websocket"
  #   values:
  #     _hide_content: true
  - scope:
      type: "futures_market_websocket_v2"
    values:
      _hide_content: true
  - scope:
      type: "futures_user_websocket"
    values:
      _hide_content: true
  - scope:
      type: "futures_documentation_cn"
    values:
      _hide_content: true
  - scope:
      type: "futures_quotes_cn"
    values:
      _hide_content: true
  - scope:
      type: "futures_order_cn"
    values:
      _hide_content: true
  - scope:
      type: "futures_entrust_cn"
    values:
      _hide_content: true
  - scope:
      type: "futures_user_cn"
    values:
      _hide_content: true
  # - scope:
  #     type: "futures_market_websocket_cn"
  #   values:
  #     _hide_content: true
  - scope:
      type: "futures_market_websocket_v2_cn"
    values:
      _hide_content: true
  - scope:
      type: "futures_user_websocket_cn"
    values:
      _hide_content: true
  - scope:
      type: "third_party_oauth"
    values:
      _hide_content: true
  - scope:
      type: "third_party_document_cn"
    values:
      _hide_content: true
  - scope:
      type: "third_party_document"
    values:
      _hide_content: true


  - scope:
      type: "user_center_documentation"
    values:
      _hide_content: true
  - scope:
      type: "user_center_account"
    values:
      _hide_content: true
  - scope:
      type: "user_center_apiKey"
    values:
      _hide_content: true
  - scope:
      type: "user_center_documentation_cn"
    values:
      _hide_content: true
  - scope:
      type: "user_center_account_cn"
    values:
      _hide_content: true
  - scope:
      type: "user_center_apikey_cn"
    values:
      _hide_content: true
# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css
